### ISSUE TITLE
Проблема со шрифтами

### ISSUE THREAD

**Issue by KrutNA** [Widowan/hackathon-fit-2022#22]
"Игры со шрифтами" до хорошего не доводят, лучше убрать и не форсить пользователям своё. С самого начала весьма сомнительная идея, от которой стоит отказаться.

@Kedr123

**Comment by Kedr123** [comment]
> "Игры со шрифтами" до хорошего качества не доводятся, лучше убрать и не форсить пользователей. С самого начала весьма сомнительна идея, от которой предпочтение.
> 
> @Kedr123

Да блин, был бы у нас нормальный дизайнер, такого говна не было бы

**Comment by KrutNA** [comment]
> > "Игры со шрифтами" до хорошего качества не доводятся, лучше убрать и не форсить пользователей. С самого начала весьма сомнительна идея, от которой предпочтение.
> > @Kedr123
> 
> Да блин, был бы у нас нормальный дизайнер, такого говна не было бы

В таком случае тем более лучше не стоит применять весьма спорные решения. И существующую проблему стоит исправить.
