### ISSUE TITLE
Визуальный баг на странице аутентификации

### ISSUE THREAD

**Issue by KrutNA** [Widowan/hackathon-fit-2022#23]
### Steps to reproduce:
1. Открыть главную страницу. На странице отображается форма регистрации.
2. Перейти на страницу входа в профиль путём нажатия кнопки "Вход".

### Expected behaviour:
Открывается чистая форма входа.

### Actual behaviour:
Открывается форма входа с ошибками с формы регистрации о пустых полях.

### Additions:
Пустое поле возможно приводит к ошибке "Данный ник уже занят!".

Опечатка в выводе ошибки "Пороли не совпадают!"

@Kedr123

**Comment by Kedr123** [comment]
Формы просто ещё недовёрстаны

> ### Шаги для воспроизведения:
> 1. Открыть главную страницу. На странице отображается форма регистрации.
> 2. Перейти на страницу входа в профиль путём нажатия кнопки "Вход".
> 
> ### Ожидаемое поведение:
> Открывается чистая форма входа.
> 
> ### Фактическое поведение:
> Открывается форма входа с ошибками с формы регистрации о пустых полях.
> 
> ### Дополнения:
> Пустое поле возможно приводит к ошибке "Данный ник уже занят!".
> 
> Опечатка в выводе ошибки "Пороли не совпадают!"
> 
> @Kedr123
