### ISSUE TITLE
Нарушение соглашения об именовании

### ISSUE THREAD

**Issue by KrutNA** [Widowan/hackathon-fit-2022#24]
https://github.com/Widowan/hackathon-fit-2022/blob/45bc77f135fa027aa86b92cec2f34295a0ebf952/backend/src/main/java/com/hypnotoad/hackathon/fit2022/backend/responses/auth/GetMeResponse.java#L7

Возможное исправление: `Me` -> `me`

@Widowan

**Comment by Widowan** [comment]
Закрыто #35, коммит [b462611](https://github.com/Widowan/hackathon-fit-2022/commit/b46261188a2f696ebce804281d01802a5ce76c39)
